/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as EngagementsRouteImport } from './routes/engagements'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as EngagementsIndexRouteImport } from './routes/engagements.index'
import { Route as EngagementsEngagementIdRouteImport } from './routes/engagements.$engagementId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementsRoute = EngagementsRouteImport.update({
  id: '/engagements',
  path: '/engagements',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementsIndexRoute = EngagementsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EngagementsRoute,
} as any)
const EngagementsEngagementIdRoute = EngagementsEngagementIdRouteImport.update({
  id: '/$engagementId',
  path: '/$engagementId',
  getParentRoute: () => EngagementsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/engagements': typeof EngagementsRouteWithChildren
  '/plugins': typeof PluginsRoute
  '/settings': typeof SettingsRoute
  '/engagements/$engagementId': typeof EngagementsEngagementIdRoute
  '/engagements/': typeof EngagementsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/plugins': typeof PluginsRoute
  '/settings': typeof SettingsRoute
  '/engagements/$engagementId': typeof EngagementsEngagementIdRoute
  '/engagements': typeof EngagementsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/engagements': typeof EngagementsRouteWithChildren
  '/plugins': typeof PluginsRoute
  '/settings': typeof SettingsRoute
  '/engagements/$engagementId': typeof EngagementsEngagementIdRoute
  '/engagements/': typeof EngagementsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/engagements'
    | '/plugins'
    | '/settings'
    | '/engagements/$engagementId'
    | '/engagements/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/plugins'
    | '/settings'
    | '/engagements/$engagementId'
    | '/engagements'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/engagements'
    | '/plugins'
    | '/settings'
    | '/engagements/$engagementId'
    | '/engagements/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  EngagementsRoute: typeof EngagementsRouteWithChildren
  PluginsRoute: typeof PluginsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagements': {
      id: '/engagements'
      path: '/engagements'
      fullPath: '/engagements'
      preLoaderRoute: typeof EngagementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagements/': {
      id: '/engagements/'
      path: '/'
      fullPath: '/engagements/'
      preLoaderRoute: typeof EngagementsIndexRouteImport
      parentRoute: typeof EngagementsRoute
    }
    '/engagements/$engagementId': {
      id: '/engagements/$engagementId'
      path: '/$engagementId'
      fullPath: '/engagements/$engagementId'
      preLoaderRoute: typeof EngagementsEngagementIdRouteImport
      parentRoute: typeof EngagementsRoute
    }
  }
}

interface EngagementsRouteChildren {
  EngagementsEngagementIdRoute: typeof EngagementsEngagementIdRoute
  EngagementsIndexRoute: typeof EngagementsIndexRoute
}

const EngagementsRouteChildren: EngagementsRouteChildren = {
  EngagementsEngagementIdRoute: EngagementsEngagementIdRoute,
  EngagementsIndexRoute: EngagementsIndexRoute,
}

const EngagementsRouteWithChildren = EngagementsRoute._addFileChildren(
  EngagementsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  EngagementsRoute: EngagementsRouteWithChildren,
  PluginsRoute: PluginsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
